# This is a basic workflow to help you get started with Actions

name: CI Debug

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "v0.1-CI-debug" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# matrix setup for multiple versions and OSs
# License: MIT

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        rakudo-version:
          - "2020.12"
      fail-fast: false
    uses: vrurg/raku-build-tools/.github/workflows/default-test-workflow.yml@workflow-v1
    with:
      os: ${{ matrix.os }}
      rakudo-version: ${{ matrix.rakudo-version }}
    - run: raku -I. t/003-declaration.rakutest
