# This is a basic workflow to help you get started with Actions

name: CI Debug

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "v0.1-CI-debug" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# matrix setup for multiple versions and OSs
# License: MIT

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        rakudo-version:
          - "2020.12"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Raku/setup-raku@v1
        name: Prepare Rakudo ${{ inputs.rakudo-version }} environment
        with:
          raku-version: ${{ inputs.rakudo-version }}
      - uses: actions/checkout@v3
        name: Checkout zef
        with:
          repository: 'ugexe/zef'
          ref: ${{ inputs.zef-version }}
          path: 'zef'
      - name: Install new zef ${{ inputs.zef-version }}
        working-directory: zef
        run: |
          raku -I. bin/zef install .
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          submodules: recursive
          path: 'main'
      - name: Versions Report
        run: |
          raku -v
          zef --version
      - run: raku -I. t/003-declaration.rakutest
